### ISSUE TITLE
Interactive issue

### ISSUE THREAD

**Issue by intBear** [NVIDIAGameWorks/kaolin-wisp#153]
When I try to run main_nerf.py, I successfully loaded the data, but the interactive renderer was crushed due to the following errors:
```
2023-05-11 20:07:33,458|    INFO| [i] Running at 60 frames/second
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\kaolin-wisp-main\app\nerf\main_nerf.py", line 491, in <module>
    app.run()  # Run in interactive mode
  File "C:\Users\admin\PycharmProjects\kaolin-wisp-main\wisp\renderer\app\wisp_app.py", line 253, in run
    app.run()   # App clock should always run as frequently as possible (background tasks should not be limited)
  File "C:\Users\admin\.conda\envs\wisp\lib\site-packages\glumpy\app\__init__.py", line 317, in run
    clock = __init__(clock=clock, framerate=framerate, backend=__backend__)
  File "C:\Users\admin\.conda\envs\wisp\lib\site-packages\glumpy\app\__init__.py", line 277, in __init__
    window.dispatch_event('on_resize', window._width, window._height)
  File "C:\Users\admin\.conda\envs\wisp\lib\site-packages\glumpy\app\window\event.py", line 396, in dispatch_event
    if getattr(self, event_type)(*args):
  File "C:\Users\admin\PycharmProjects\kaolin-wisp-main\wisp\renderer\app\wisp_app.py", line 555, in on_resize
    self.cugl_rgb_handle = self._register_cugl_shared_texture(tex)
  File "C:\Users\admin\PycharmProjects\kaolin-wisp-main\wisp\renderer\app\wisp_app.py", line 331, in _register_cugl_shared_texture
    handle = cuda_register_gl_image(image=int(tex.handle), target=tex.target)
  File "C:\Users\admin\PycharmProjects\kaolin-wisp-main\wisp\renderer\core\cuda.py", line 57, in cuda_register_gl_image
    raise RuntimeError('Failed to register GL texture as a CUDA shared resource.')
RuntimeError: Failed to register GL texture as a CUDA shared resource.

Process finished with exit code 1

```
Although I tried to recreate conda env based on the tutorial, this issue still exists.

**Comment by orperel** [comment]
1. Are you connected to a display?
2. Is `cuda-python` installed properly?
3. You can also bypass GL texture registration by pulling this PR: https://github.com/NVIDIAGameWorks/kaolin-wisp/pull/118
There is a workaround in [these lines](https://github.com/NVIDIAGameWorks/kaolin-wisp/pull/118/files#diff-d13f3ce350b22c0df28a364d45ab84fd0c5f7312f866591151c79ad61dde81eeL321-R343) for your error message.
