### ISSUE TITLE
version `GLIBCXX_3.4.30' not found in docker image

### ISSUE THREAD

**Issue by shota3506** [NVIDIAGameWorks/kaolin-wisp#22]
Thanks for this amazing library!

Let me ask about running example application on docker image.
I created an docker image following [this](https://github.com/NVIDIAGameWorks/kaolin-wisp#1-using-our-dockerfile-linux-only) documentation and tried to run NGLOG-NeRF with:
```bash
python3 app/main.py --config configs/nglod_nerf.yaml --dataset-path ./datasets/V8 --dataset-num-workers 4
```
(I mounted V8 data to /wisp/datasets)

Then I got this error message
```
Traceback (most recent call last):
  File "/wisp/app/main.py", line 13, in <module>
    from wisp.trainers import *
  File "/wisp/wisp/__init__.py", line 9, in <module>
    from . import ops
  File "/wisp/wisp/ops/__init__.py", line 10, in <module>
    from . import grid
  File "/wisp/wisp/ops/grid.py", line 10, in <module>
    from kaolin import _C
  File "/kaolin/kaolin/__init__.py", line 1, in <module>
    from . import io
  File "/kaolin/kaolin/io/__init__.py", line 5, in <module>
    from . import render
  File "/kaolin/kaolin/io/render.py", line 23, in <module>
    from ..render.camera import generate_perspective_projection
  File "/kaolin/kaolin/render/__init__.py", line 2, in <module>
    from . import mesh
  File "/kaolin/kaolin/render/mesh/__init__.py", line 1, in <module>
    from .utils import *
  File "/kaolin/kaolin/render/mesh/utils.py", line 22, in <module>
    from ... import ops
  File "/kaolin/kaolin/ops/__init__.py", line 8, in <module>
    from . import voxelgrid
  File "/kaolin/kaolin/ops/voxelgrid.py", line 18, in <module>
    from scipy import ndimage
  File "/opt/conda/lib/python3.9/site-packages/scipy/__init__.py", line 155, in <module>
    from . import fft
  File "/opt/conda/lib/python3.9/site-packages/scipy/fft/__init__.py", line 79, in <module>
    from ._helper import next_fast_len
  File "/opt/conda/lib/python3.9/site-packages/scipy/fft/_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/opt/conda/lib/python3.9/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/opt/conda/lib/python3.9/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/conda/lib/python3.9/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-39-x86_64-linux-gnu.so)
```

Do you have any ideas about this error?
I'm using ubuntu 22.04 as a host machine 

Thanks in advance

**Comment by haganelego** [comment]
Thank you for your great work!

I got same issue on Ubuntu 20.04
When I build the kaolin docker image, I founf the error message below.
```
Error processing line 1 of /opt/conda/lib/python3.9/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/opt/conda/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
```
Is it related to this issue?

**Comment by Ahanio** [comment]
Hi all!
I had the same issue. Solved it by changing the scipy version in [requirements.txt](https://github.com/NVIDIAGameWorks/kaolin-wisp/blob/main/requirements.txt#L13):
`scipy==1.7.2`
