### ISSUE TITLE
cannot import name 'Camera' from 'kaolin.render.camera'

### ISSUE THREAD

**Issue by YifuTao** [NVIDIAGameWorks/kaolin-wisp#6]
Hi, thanks for this wonderful project code release!

I followed the instructions and installed kaolin-wisp, but when I import wisp I get:

        >>> import wisp
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          File "/home/yifu/workspace/kaolin-wisp/wisp/__init__.py", line 10, in <module>
            import wisp.config_parser
          File "/home/yifu/workspace/kaolin-wisp/wisp/config_parser.py", line 15, in <module>
            from wisp.datasets import *
          File "/home/yifu/workspace/kaolin-wisp/wisp/datasets/__init__.py", line 10, in <module>
            from .multiview_dataset import MultiviewDataset
          File "/home/yifu/workspace/kaolin-wisp/wisp/datasets/multiview_dataset.py", line 13, in <module>
            from wisp.datasets.formats import load_nerf_standard_data, load_rtmv_data
          File "/home/yifu/workspace/kaolin-wisp/wisp/datasets/formats/__init__.py", line 9, in <module>
            from .rtmv import *
          File "/home/yifu/workspace/kaolin-wisp/wisp/datasets/formats/rtmv.py", line 18, in <module>
            from kaolin.render.camera import Camera, blender_coords
        ImportError: cannot import name 'Camera' from 'kaolin.render.camera' (/home/yifu/workspace/kaolin/kaolin/render/camera.py)

Importing kaolin (0.11.0) itself is working for me. I am using Python 3.8.13, PyTorch 1.12 with cuda 11.6. 

Thanks in advance!

**Comment by Caenorst** [comment]
Hi @YifuTao , thank you for your interest in Kaolin Wisp !

We will soon tag a release v0.12.0 that should work, but right now we recommend using master branch from Kaolin.

**Comment by jhzgjhzg** [comment]
When will version 0.12.0 be released

**Comment by jhzgjhzg** [comment]
When will version 0.12.0 be released? @Caenorst

**Comment by Caenorst** [comment]
Done
